services:
  yolo-client:
    image: waitheramacharia/yolo-client:v1.0.0
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - yolo-backend
    networks:
      - app-net

  yolo-backend:
    image: waitheramacharia/yolo-backend:v1.0.0
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - app-net

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - app-mongo-data:/data/db
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  app-mongo-data:
