- name: Run MongoDB container
  community.docker.docker_container:
    name: app_mongo
    image: mongo:5.0
    state: started
    restart_policy: unless-stopped
    networks:
      - name: app-net
    env:
      MONGO_INITDB_ROOT_USERNAME: "{{ mongo_root_user }}"
      MONGO_INITDB_ROOT_PASSWORD: "{{ mongo_root_pass }}"
    ports:
      - "27017:27017"
    volumes:
      - app-mongo-data:/data/db
      - mongo-config:/data/configdb
