- name: Wait for MongoDB to be ready
  wait_for:
    host: 127.0.0.1
    port: 27017
    delay: 5
    timeout: 120


- name: Run Backend container
  community.docker.docker_container:
    name: yolo_backend
    image: waitheramacharia/yolo-backend:v1.0.0
    state: started
    restart_policy: unless-stopped
    networks:
      - name: app-net
    ports:
      - "5000:5000"
    env:
      NODE_ENV: production
