- name: Wait for MongoDB to be ready
  wait_for:
    host: "{{ mongo_host }}"
    port: "{{ mongo_port }}"
    delay: 5
    timeout: 60

- name: Run Backend container
  docker_container:
    name: "{{ backend_container_name }}"
    image: "{{ backend_image }}"
    state: started
    restart_policy: unless-stopped
    published_ports:
      - "{{ backend_port }}:5000"
    networks:
      - name: "{{ docker_network_name }}"
