---
- name: Configure and run Yolo E-Commerce App using Ansible
  hosts: all
  become: true

  roles:
    - role: docker          # Installs Docker and Docker Compose
    - role: mongo           # Sets up MongoDB container
    - role: backend         # Runs backend container
    - role: frontend        # Runs frontend container

