---
- name: Configure and run Yolo E-Commerce App using Ansible
  hosts: all
  become: true

  roles:
    - { role: docker, tags: ["docker"] }
    - { role: mongo, tags: ["mongo"] }
    - { role: backend, tags: ["backend"] }
    - { role: frontend, tags: ["frontend"] }
